name: Labeler
on:
  workflow_run:
    workflows: ["Auto Need-Review labeler"]
    types:
      - completed
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name : 'Download artifact'
        uses : actions/github-script@v6
        with : 
          script : |
          
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner : context.repo.owner,
              repo : context.repo.repo,
              run_id : context.payload.workflow_run.id,
            });
            
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
                        
            let matchArtifact2 = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "review_num"
            })[0];
            
            let download2 = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact2.id,
               archive_format: 'zip',
            });

            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/review_num.zip`, Buffer.from(download2.data));

      - name: 'Unzip artifact1'
        run: unzip pr_number.zip
        
      - name: 'Unzip artifact2'
        run: unzip review_num.zip
        
      - name: 'review_count'
        id : review_count
        uses: actions/github-script@v4
        with:
          scripts: |
            let fs = require('fs');
            let review = Number(fs.readFileSync('./review_num'));
            echo "REVIEW=$review" >> $GITHUB_OUTPUT
            
      - name: Make label if approved review < 3
        if: ${{ steps.review_count.outputs.REVIEW < 3 && !contains(github.event.pull_request.labels.*.name, 'Need Review') }}
        uses: actions/github-script@v4
        with:
          script: |
            let fs = require('fs');
            let issue_number = Number(fs.readFileSync('./pr_number'));
            
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: ["Need Review"]
            })
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove label if approved review >= 3
        if: ${{ steps.review_count.outputs.REVIEW >= 3 && contains(github.event.pull_request.labels.*.name, 'Need Review') }}
        uses: actions/github-script@v4
        with:
          script: |
            let fs = require('fs');
            let issue_number = Number(fs.readFileSync('./pr_number'));
            
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              name : ["Need Review"]
            })
          token: ${{ secrets.GITHUB_TOKEN }}
