name: Auto Need-Review labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: review_count
        env:
          PR_NUMBER: ${{ github.event.number }}
          IS_CONTAIN: ${{ contains(github.event.pull_request.labels.*.name, 'Need Review') }}
        id: review_count
        run: |
          review=$(curl -s -H "Accept: application/vnd.github.black-cat-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
          | jq '[ .[] | select(.state=="APPROVED") ] | length')
          echo "Number of approved review_count: $review"
          echo "REVIEW=$review" >> $GITHUB_OUTPUT
          echo "CONTAIN?=$IS_CONTAIN"
          
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $review > ./pr/review_num
          echo $IS_CONTAIN > ./pr/contain_bool
          echo "$PR_NUMBER"
          
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
          
      - name: DEBUG
        run: |
          echo "Number of Approved review_count : ${{ steps.review_count.outputs.REVIEW }}"
