name: Auto Need-Review labeler

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  pull_request_review:
    types: [edited, dismissed, submitted]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: review_count
        id: review_count
        run: |
          review=$(curl -s -H "Accept: application/vnd.github.black-cat-preview+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
          | jq '[ .[] | select(.state=="APPROVED") ] | length')
          echo "Number of approved review_count: $review"
          echo "REVIEW=$review" >> $GITHUB_OUTPUT
          mkdir -p ./re
          echo $review > ./re/review_num
      - uses: actions/upload-artifact@v3
        with:
          name: review_num
          path: re/
          
      - name: DEBUG
        run: |
          echo "Number of Approved review_count : ${{ steps.review_count.outputs.REVIEW }}"

      - name: PR_NUM
        id: PR_NUM
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
